---
# defaults file for ansible_nodes
ssh_log_level: INFO             # Linux: Control is INFO or VERBOSE. Stricter is not approved and more verbose exposes user info
ssh_max_auth_tries: 4           # Linux: Control is 4 retries
ssh_mac_list: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"   # Linux: RHEL7 only control
ssh_ciphers_list: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"                        # Linux: Ubuntu control only
ssh_kex_list: "curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1" # Linux: Ubuntu control only
ssh_alive_interval: 300         # Linux: Control is 5 minutes
ssh_alive_count_max: 0          # Linux: Control is 0 count
ssh_grace_time: 60              # Linux: Control is for 60 seconds or less
ssh_max_sessions: 4             # Linux: Control is 4 sessions from a single host
ssh_login_banner: issue.net     # Linux: a file with no path will exist in the role's files directory, an absolute path will exist on the control host
